# Generated by Django 3.0.8 on 2020-09-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostMarcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=45)),
                ('ranuras', models.CharField(choices=[('rows of chips', 'Rows of chips'), ('3', '3'), ('4', '5'), ('2', '2'), ('1', '1')], default='ranuras', max_length=15)),
                ('frecuencia', models.CharField(choices=[('1333 mHz', '1333 MHz'), ('NO', 'NO'), ('1200 mHz', '1200 MHz'), ('2666 mHz', '2666 MHz'), ('1866 mHz', '1866 MHz'), ('2000 mHz', '2000 MHz'), ('2133 mHz', '2133 MHz'), ('2400 mHz', '2400 MHz'), ('1066 mHz', '1066 MHz'), ('1600 mHz', '1600 MHz')], default='frecuencia', max_length=15)),
                ('SSD', models.CharField(choices=[('NO', 'NO'), ('m.2 sata', 'M.2 SATA'), ('especifica', 'SE ESPECIFICA EN NOTAS'), ('2.5" sata', '2.5" SATA'), ('m.2 pcie', 'M.2 PCIE')], default='type_ssd', max_length=20)),
                ('HDD', models.CharField(choices=[('3.5m', 'Mecanico 3.5'), ('2.5m', 'Mecanico 2.5'), ('NO', 'NO'), ('especifica', 'SE ESPECIFICA EN NOTAS')], default='type_hdd', max_length=20)),
                ('notas', models.TextField()),
                ('imagePortada', models.ImageField(blank=True, null=True, upload_to='')),
                ('marca', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppEquipos.PostMarcas')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEquipos.Post')),
            ],
        ),
    ]
